apiVersion: v1
kind: Service
metadata:
  name: {{ include "phplogin.fullname" . }}
  labels:
    {{- include "phplogin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "phplogin.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: phplogin-helm-lb
spec:
  selector:
    app: phplogin-helm
  loadBalancerIP: 172.26.16.63
  ports:
    - port: 8383
      targetPort: 80
      name: phplogin-helm-lb
  type: LoadBalancer