apiVersion: v1
kind: Service
metadata:
  name: phplogin-lb
spec:
  selector:
    app: phplogin
  loadBalancerIP: 172.26.16.63
  ports:
    - port: 8181
      targetPort: 80
  type: LoadBalancer