apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'phploginv8.0'
  labels:
    app: web
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        octopusexport: OctopusExport
    spec:
      hostNetwork: true
      volumes:
        - name: mydata
          persistentVolumeClaim:
            claimName: phplogindisk
      containers:
        - name: phplogin
          image: 'ghcr.io/amundead/phplogin:8.0'
          ports:
            - name: phploginlb
              expose: true
              protocol: TCP
              containerPort: 8181
              _serviceType: LoadBalancer
              _ipam: dhcp
              _listeningPort: 80
          env:
            - name: MYSQL_DATABASE
              value: demo
            - name: MYSQL_PASSWORD
              value: root_password
            - name: MYSQL_USERNAME
              value: root
            - name: MYSQL_HOST
              value: 'localhost:3360'
          volumeMounts:
            - name: phplogindisk
              mountPath: /var/www/html
              subPath: app
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
