apiVersion: apps/v1
kind: Deployment
metadata:
  name: phploginv8.0
  labels:
    app: web
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        octopusexport: OctopusExport
    spec:
      hostNetwork: false
      #volumes:
        #- name: phplogin-disk
          #persistentVolumeClaim:
            #claimName: phploginpvc
      containers:
        - name: phplogin
          image: 'ghcr.io/amundead/phplogin:8.0'
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              value: demo
            - name: MYSQL_PASSWORD
              value: root_password
            - name: MYSQL_USERNAME
              value: root
            - name: MYSQL_HOST
              value: 'localhost:3360'
          #volumeMounts:
            #- name: phplogin-disk
              #mountPath: /var/www/html/app
              #subPath: picture
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
