apiVersion: v1
kind: Service
metadata:
annotations:
  #cloudprovider.harvesterhci.io/ipam: dhcp
  field.cattle.io/publicEndpoints: >-
    [{"addresses":["172.26.16.63"],"port":8181,"protocol":"TCP","serviceName":"application-testing:phplogin-lb","allNodes":false}]
name: phplogin-lb
spec:
  selector:
    app: phplogin
  loadBalancerIP: 172.26.16.63
  ports:
    - port: 8181
      targetPort: 80
  type: LoadBalancer